ansible-community/ansible-build-data

2.10/acd.in

`grep redirect lib/ansible/config/routing.yml | perl -n -e'/redirect: (\w+\.\w+)\./ && print "$1\n"' | sort -u` from WIP branch where I'm fixing routing.yml

Extra Collections to include in ACD

---

2.10/acd.in

These collections have been built https://galaxy.ansible.com/community/

Add built collections

---

2.10/acd.in

dedicated collection for exoscale.com

dedicated collection for exoscale.com related plugins

---

2.10/acd.in

* Things have once again moved around, so update naming
* Hetzner.hcloud should have a release in a week
* I've raised an issue against Dellemc
* I'm helping mellanox.onyx (which has just span out of community.network)
Generated using `grep redirect lib/ansible/config/ansible_builtin_runtime.yml | perl -n -e'/redirect: (\w+\.\w+)\./ && print "$1\n"' | sort -u `, though that list contains the following errors:
* checkpoint is a typo and being fixed
* splunk.enterprise_security should be splunk.es. That will be fixed shortly

Update list of collections to include

---

2.10/acd.in

https://galaxy.ansible.com/mellanox/onyx have released `0.1.0`

mellanox.onyx has been released

---

2.10/acd.in

community.proxysql has had it's first release

community.proxysql 0.1.0

---

2.10/acd.in

See https://github.com/ansible-collections/dellemc.os10/issues/20#issuecomment-661680127

dellemc.os10 0.1.0-dev1 has been published to galaxy

---

2.10/CHANGELOG-v2.10.rst

Changes from ansible-community/antsibull#162

Reorganize sections

---

2.10/CHANGELOG-v2.10.rst
2.10/changelog.yaml

Also adds release summary for 2.10.0a7.

Link to porting guides and mention date in release summary

---

2.10/CHANGELOG-v2.10.rst
2.10/collection-meta.yaml

Fixes #28. Needs PR in antsibull to actually use this information.

Add manual collection metadata

---

2.10/CHANGELOG-v2.10.rst
2.10/changelog.yaml

Contains the changes from #23 that have are in the latest released collections' changelogs.

Reduce changelog for AWS and vmware collections

---

2.10/changelog.yaml

@felixfontein @acozine @samccann

Add known bugs to the 2.10 changelog/porting guide.

---

2.10/CHANGELOG-v2.10.rst

Will add a fix to antsibull later which prevents this in the first place.

Remove bad part of changelog

---

2.10/ansible.in

1.0.0 has just been released, and IMO all points from https://github.com/ansible-collections/overview/blob/main/collection_requirements.rst are satisfied.

Add community.docker

---

2.10/ansible.in

1.0.0 has just been released, and IMO all points from https://github.com/ansible-collections/overview/blob/main/collection_requirements.rst are satisfied.
CC @Andersson007

Add community.postgresql

---

2.10/ansible.in

1.0.0 has just been released, and IMO all points from https://github.com/ansible-collections/overview/blob/main/collection_requirements.rst are satisfied.

Add community.routeros

---

2.10/CHANGELOG-v2.10.rst

Result of https://github.com/ansible-community/antsibull/pull/225

Update generated changelog

---

2.10/ansible-2.10.build
2.10/ansible.in
3/ansible.in

Add community.fortios

---

3/ansible.in

See the reviews in https://github.com/ansible-collections/ansible-inclusion/discussions/6 by @Andersson007, @jillr and myself.
CC @tadeboro

Add sensu.sensu_go to Ansible 3.0.0

---

3/ansible.in

Application and reviews are available at https://github.com/ansible-collections/ansible-inclusion/discussions/9

Add community.sops Ansible Collection

---

3/ansible.in
3/collection-meta.yaml

Application and reviews are visible at https://github.com/ansible-collections/ansible-inclusion/discussions/8

Add inspur.sm Ansible Collection

---

2.10/ansible.in
3/ansible.in
3/collection-meta.yaml

Add ansible.utils to collection list
Repo: https://github.com/ansible-collections/ansible.utils
Galaxy: https://galaxy.ansible.com/ansible/utils

Add ansible.utils to Ansible 3.0.0 collection list

---

4/ansible.in
4/collection-meta.yaml

Add new collections decided on today's community meeting

---

4/CHANGELOG-v4.rst

Application of ansible-community/antsibull#285.

Remove duplicate new module/plugin/object entries

---

5/ansible.in
5/collection-meta.yaml

As approved in https://meetbot.fedoraproject.org/ansible-community/2021-09-15/ansible_community_meeting.2021-09-15-18.00.html.
ref: https://github.com/ansible-community/community-topics/issues/32

Add community.ciscosmb and community.dns for Ansible 5

---

4/CHANGELOG-v4.rst
4/porting_guide_4.rst
5/CHANGELOG-v5.rst
5/porting_guide_5.rst

Result of https://github.com/ansible-community/antsibull/pull/363

Mention new collections

---

README.md

Relates to https://github.com/ansible-community/ansible-build-data/pull/103
Adds info how to add new collection to a build

README: add a paragraph about adding collections

---

5/ansible-5.build
5/ansible.in
5/collection-meta.yaml
6/ansible-6.build
6/ansible.in
6/collection-meta.yaml

Implements https://github.com/ansible-community/community-topics/issues/101

Add cisco.dnac to Ansible 5 and 6

---

5/ansible-5.build
5/ansible.in
5/changelog.yaml
5/collection-meta.yaml
6/ansible-6.build
6/ansible.in
6/changelog.yaml
6/collection-meta.yaml

Start renaming process for community.sap -> community.sap_libs

---

6/changelog.yaml

Can be merged once https://github.com/ansible-community/antsibull/pull/429 is merged.
CC @Ompragash

Add changelog fragment for the ansible-community CLI tool

---

6/ansible-6.build
6/ansible.in
6/collection-meta.yaml
7/ansible.in
7/collection-meta.yaml

Relates to https://github.com/ansible-community/community-topics/issues/117

Add purestorage.fusion to ansible 6

---

.github/workflows/antsibull-build.yml

CI: remove testing against Ansible 5

CI: remove testing against Ansible 5

---

README.md

README: Add info about milestones

README: Add info about milestones

---

6/ansible-6.build
6/ansible.in
6/collection-meta.yaml
7/ansible.in
7/collection-meta.yaml

Add inspur.ispim to Ansible 6
Implements https://github.com/ansible-community/community-topics/issues/129

Add inspur.ispim to Ansible 6

---

6/ansible-6.build
6/ansible.in
6/collection-meta.yaml
7/ansible.in
7/collection-meta.yaml

See https://github.com/ansible-community/community-topics/issues/137
CC @resmo @Andersson007 @Ompragash

Add vultr.cloud to Ansible 6 and 7

---

7/changelog.yaml

Announce Python 3.9 requirement in changelog

---

6/ansible-6.build
6/ansible.in
6/collection-meta.yaml
7/ansible-7.build
7/ansible.in
7/collection-meta.yaml

Add loylydba.sqlserver collection to Ansible 6 and 7
Fixes https://github.com/ansible-community/community-topics/issues/149

Add loylydba.sqlserver collection to Ansible 6 and 7

---

7/ansible-7.build
7/ansible.in
7/collection-meta.yaml
8/ansible.in
8/collection-meta.yaml

Relates to:
- https://github.com/ansible-community/community-topics/issues/163
- https://github.com/ansible-collections/ansible-inclusion/discussions/52

Ansible 7/8: Add grafana.grafana collection

---

7/ansible-7.build
7/ansible.in
7/collection-meta.yaml
8/ansible.in
8/collection-meta.yaml

Implement ansible-community/community-topics#163

Ansible 7/8: Add dellemc.unity collection

---

7/ansible-7.build
7/ansible.in
7/collection-meta.yaml
8/ansible.in
8/collection-meta.yaml

Implement ansible-community/community-topics#177

Ansible 7/8: Add dellemc.powerflex collection

---

7/ansible-7.build
7/ansible.in
7/collection-meta.yaml
8/ansible.in
8/collection-meta.yaml

Implement ansible-community/community-topics#217

Ansible 7/8: Add microsoft.ad collection

---

docs/CONVENTIONS.md
docs/policies.md

This needs some more work, but I wanted to put up a draft to give more context to https://github.com/ansible-community/ansible-build-data/pull/222.

add release documentation scaffolding

---

7/validate-tags-ignores
8/validate-tags-ignores

Upstream has resolved the issue.

remove hpe.nimble from validate-tags-ignores

---

7/ansible-7.build

Ref: https://github.com/ansible-collections/dellemc.enterprise_sonic/issues/268.
Ref: #223

Pin dellemc.enterprise_sonic to 2.0.0 in Ansible 7

---

8/ansible-8.build

Ref: https://github.com/ansible-collections/hetzner.hcloud/issues/217
Ref: #223

Pin hetzner.hcloud to 1.11.0 in Ansible 8

---

7/changelog.yaml
8/changelog.yaml

Deprecate gluster.gluster as discussed in ansible-community/community-topics#225 and voted on in ansible-community/community-topics#241

Deprecate gluster.gluster

---

8/changelog.yaml

FIX C&P error from PR 248

---

9/changelog.yaml

Relates: https://github.com/ansible-community/antsibull/pull/530

9: add changelog entry for setup.cfg configuration

---

8/ansible-8.build

hetzner.hcloud now vendors their Python requirement that needs constant updating.
Ref: #223
Ref: https://github.com/ansible-collections/hetzner.hcloud/issues/217

Un-pin hetzner.hcloud. Make sure some versions are not taken.

---

8/changelog.yaml
9/changelog.yaml

Deprecate netapp.azure as discussed in ansible-community/community-topics#234 and voted on in ansible-community/community-topics#249

Deprecate netapp.azure

---

8/changelog.yaml
9/changelog.yaml

Deprecate community.azure as discussed in ansible-community/community-topics#263 and voted on in ansible-community/community-topics#264

Deprecate community.azure

---

9/validate-tags-ignores

Ref: https://github.com/CiscoDevNet/intersight-ansible/issues/93

Ansible 9 CI: ignore missing tag for cisco.intersight for now

---

9/validate-tags-ignores

This reverts commit 3b42722c5f0f0127956a7a9b021129ce3919ba33.
See https://github.com/CiscoDevNet/intersight-ansible/issues/93#issuecomment-1714038831.

Revert "Ignore missing tag for cisco.intersight. (#287)"

---

8/ansible-8.constraints
9/ansible-9.constraints

Needs https://github.com/ansible-community/antsibull/pull/546 to work.

Exclude collections whose releases aren't tagged with constraints files

---

8/ansible-8.constraints
9/ansible-9.constraints

Ref: https://github.com/ansible-community/ansible-build-data/issues/223#issuecomment-1732932405

Remove constraints for netapp.* collections

---

8/ansible-8.constraints
9/ansible-9.constraints

Ref: https://github.com/ansible-community/ansible-build-data/issues/223#issuecomment-1794087998
Fixes: https://github.com/fortinet-ansible-dev/ansible-galaxy-fortios-collection/issues/277

Remove fortinet.fortios constraint

---

9/galaxy-requirements.yaml

Update Galaxy requirements for 9.0.0b1

---

8/collection-meta.yaml
9/collection-meta.yaml

chocolatey.chocolatey has its galaxy.yml and collection code in a
subdirectory.

set collection-directory for chocolatey.chocolatey

---

8/collection-meta.yaml
9/collection-meta.yaml

Ref: https://github.com/ansible-community/community-topics/issues/234#issuecomment-1795492691
@suhasbshekar @wenjun666 @chuyich please approve this PR to acknowledge that you are being added as maintainers for these collections. Thanks.

Update maintainers list for some netapp.* collections

---

10/ansible-10.constraints
8/ansible-8.constraints
9/ansible-9.constraints

Relates: https://github.com/cisco-en-programmability/dnacenter-ansible/issues/133
Relates: https://github.com/meraki/dashboard-api-ansible/issues/38

Pin `cisco.dnac` and `cisco.meraki` due to compatibility issues

---

10/ansible-10.constraints
8/ansible-8.constraints
9/ansible-9.constraints

Closes https://github.com/cisco-en-programmability/dnacenter-ansible/issues/142

Remove cisco.dnac constraint

---

10/ansible-10.constraints
8/ansible-8.constraints
9/ansible-9.constraints

Ref: https://github.com/ansible-collections/ibm.storage_virtualize/issues/36#issuecomment-1865750955

Remove ibm.storage_virtualize constraint

---

10/ansible.in
10/collection-meta.yaml
9/ansible-9.build
9/ansible.in
9/collection-meta.yaml

Implement ansible-community/community-topics#283

Add community.library_inventory_filtering_v1 collection

---

10/changelog.yaml
9/changelog.yaml

Deprecate inspur.sm as discussed and voted on in [Unmaintained collection: inspur.sm](https://forum.ansible.com/t/2854).

Deprecate inspur.sm

---

10/ansible-10.constraints
9/ansible-9.constraints

Ref: https://github.com/Infinidat/ansible-infinidat-collection/issues/20

Add constraints: infinidat.infinibox 1.4.0 is not tagged

---

9/ansible-9.constraints

Ref: https://github.com/ansible-collections/community.ciscosmb/issues/75
Ref: https://github.com/ansible-community/ansible-build-data/issues/223#issuecomment-2072716702

Add constraint to avoid breaking change in community.ciscosmb

---

.github/workflows/ansible-release.yml

Ref: https://github.com/ansible-community/ansible-build-data/pull/390#discussion_r1578364641

Release workflow: simplify pip install

---

.github/workflows/ansible-release.yml

Release workflow: tag the PR's merge commit (and not HEAD)

---

9/ansible-9.constraints

Ref: ansible-collections/community.grafana#367
Ref: [#223 (comment)](https://github.com/ansible-community/ansible-build-data/issues/223#issuecomment-2122075628)

Add constraint to avoid breaking change in community.grafana

---

9/ansible-9.constraints

https://github.com/ansible-collections/community.grafana/issues/367 has been fixed with the new [release 1.9.1](https://github.com/ansible-collections/community.grafana/blob/main/CHANGELOG.rst#v191).

Remove constraint for community.grafana in Ansible 9

---

10/ansible-10.constraints
9/ansible-9.constraints

Ref: https://github.com/cyberark/ansible-security-automation-collection/issues/71
Ref: https://github.com/ansible-community/ansible-build-data/issues/223#issuecomment-2143547911

Restrict cyberark.pas to < 1.0.27

---

10/porting_guide_10.rst

This change manually includes details from the 2.17.0 changelog that were not included in the porting guide.
Relates to https://github.com/ansible/ansible-documentation/pull/1523

Detail about playbook conditionals from changelog

---

10/ansible-10.build
10/ansible.in
10/collection-meta.yaml
11/ansible.in
11/collection-meta.yaml

Ref: https://forum.ansible.com/t/5084
Ref: https://github.com/ansible-collections/ansible-inclusion/discussions/70#discussioncomment-9650554
I would suggest to wait a few days before merging this, in case we need to do an emergency 10.0.1 release for whatever (unexpected) reason. If we haven't done one in a few days it's safe to assume the next release will be 10.1.0, which accepts new features (and thus new collections).

Add kubevirt.core to Ansible 10 and 11

---

10/ansible-10.build
10/ansible.in
10/collection-meta.yaml
11/ansible.in
11/collection-meta.yaml

Ref: https://forum.ansible.com/t/6209
Ref: ansible-collections/ansible-inclusion#66

Add ieisystem.inmanage to Ansible 10 and 11

---

10/collection-meta.yaml
11/collection-meta.yaml
9/collection-meta.yaml

As announced in the last community meeting, I would like to sort collection-meta.yaml alphabetically.
I've sorted this with `grep '^  [^ ]' collection-meta.yaml | sort` and there might be differences between locales, but I think it's an improvement to the current situation.
_edit_: +455 / -455 lines, so it looks like I didn't drop any information accidentally :-)

Sort collection-meta.yaml

---

9/ansible-9.build
9/ansible.in
9/collection-meta.yaml

Follow-up to #431.
Ref: https://github.com/ansible-community/ansible-build-data/pull/439#issuecomment-2198647436

Add ieisystem.inmanage to Ansible 9 as well

---

10/ansible-10.constraints
11/ansible-11.constraints
9/ansible-9.constraints

Ref: https://github.com/cyberark/ansible-security-automation-collection/tags
Ref: https://github.com/cyberark/ansible-security-automation-collection/issues/71#issuecomment-2284249294

cyberark.pas 1.0.27 has been tagged by now

---

.github/workflows/antsibull-build.yml

It will soon be a dependency of antsibull / its subprojects.

Check out antsibull-fileutils as well

---

10/collection-meta.yaml
11/collection-meta.yaml
9/collection-meta.yaml

Add removal information to collection-meta.yaml

---

docs/automated-process.md
docs/release-process.md

Ref: https://github.com/ansible-community/antsibull/pull/626

Add instructions for EOL releases

---

10/changelog.yaml
10/collection-meta.yaml
11/changelog.yaml
11/collection-meta.yaml
9/changelog.yaml
9/collection-meta.yaml

Relates: https://github.com/ansible-community/ansible-build-data/issues/463
_edit:_ [vote on the forum](https://forum.ansible.com/t/8380/2)

Schedule sensu.sensu_go for removal in Ansible 12

---

10/collection-meta.yaml
11/collection-meta.yaml
8/collection-meta.yaml
9/collection-meta.yaml

Standardize info for collections maintained by the Ansible Cloud Team

Standardize info for collections maintained by the Ansible Cloud Team

---

10/collection-meta.yaml
11/collection-meta.yaml
9/collection-meta.yaml

Relates: https://forum.ansible.com/t/8030
Relates: https://github.com/ansible-community/ansible-build-data/issues/475

Schedule community.network for removal in Ansible 12

---

.yamllint
10/changelog.yaml
11/changelog.yaml
9/changelog.yaml

Ref: https://github.com/ansible-community/antsibull-build/pull/638

Reformat changelog

---

11/ansible-11.constraints
12/ansible-12.constraints

Ref: https://github.com/ansible-community/ansible-build-data/issues/223#issuecomment-2557617982
Ref: https://github.com/meraki/dashboard-api-ansible/issues/76

Pin cisco.meraki to < 2.20.0

---

11/ansible-11.constraints
12/ansible-12.constraints
8/ansible-8.constraints
9/ansible-9.constraints

Closes https://github.com/meraki/dashboard-api-ansible/issues/76
Ref: https://github.com/meraki/dashboard-api-ansible/issues/76#issuecomment-2566130097
Ref: https://github.com/ansible-community/ansible-build-data/issues/223#issuecomment-2557617982

Revert cisco.meraki pin

---

11/ansible-11.constraints
12/ansible-12.constraints

Ref: https://github.com/ansible-collections/ibm.storage_virtualize/issues/57
Ref: https://github.com/ansible-community/ansible-build-data/issues/223#issuecomment-2749183864

Restrict ibm.storage_virtualize to <2.7.2

---

11/ansible-11.build
11/ansible.in
11/collection-meta.yaml
12/ansible.in
12/collection-meta.yaml

Ref: https://forum.ansible.com/t/41262
Ref: ansible-collections/ansible-inclusion#79

[Default date 2025-04-16] Add hitachivantara.vspone_block to Ansible 11+

---

12/porting_guide_12.rst

Apply changes from https://github.com/ansible-community/antsibull-build/pull/663.

Fix Ansible 12 porting guide

---

11/ansible-11.constraints
12/ansible-12.constraints
8/ansible-8.constraints

Ref: https://github.com/cyberark/ansible-security-automation-collection/issues/83
Ref: #223

Restrict cyperark.pas to <1.0.31

---

11/ansible-11.constraints
12/ansible-12.constraints
8/ansible-8.constraints

This reverts commit 7ca1da6714bc44efdda66f624baf0a30c2420744.
Ref: https://github.com/cyberark/ansible-security-automation-collection/issues/83
Ref: #223

Revert "Restrict cyperark.pas to <1.0.31. (#541)"

---

12/porting_guide_12.rst

Uses https://github.com/ansible-community/antsibull-changelog/pull/203 and https://github.com/ansible-community/antsibull-build/pull/665.

Ansible 12 porting guide: use correct underlines for subsubsections

---

12/ansible-12.build
12/ansible-12.constraints
12/ansible.in
12/collection-meta.yaml

Ref: https://forum.ansible.com/t/43367/10

Remove cisco.ise from Ansible 12

---

docs/automated-process.md

Update automated-process.md to fix typo

---

12/ansible-12.constraints

Ref: https://github.com/ansible-community/ansible-build-data/issues/223#issuecomment-3036898402
Ref: https://github.com/ansible-collections/vmware.vmware_rest/issues/613

Ansible 12: restrict vmware.vmware_rest to < 4.8.0

---

12/ansible-12.constraints

This reverts commit 0a8fcf778ea17defe1ea7a0547ea0494ba1359dd.
Ref: https://github.com/ansible-collections/vmware.vmware_rest/issues/613

Revert "Restrict vmware.vmware_rest to < 4.8.0. (#567)"

---

docs/automated-process.md

This PR adds the initial setup information (such as Build Steps, links etc) required for any release manager to start and successful completion of the task.

Updates automated workflow with initial setup information

---

11/ansible-11.build
11/ansible.in
11/collection-meta.yaml

The subset of #579 that affects Ansible 11.

Add ravendb.ravendb to Ansible 11

---

11/ansible-11.constraints
12/ansible-12.constraints

Ref: https://github.com/ansible-community/ansible-build-data/pull/595#issuecomment-3246257755
Ref: https://github.com/Pure-Storage-Ansible/FlashBlade-Collection/pull/369#issuecomment-3246253862

Restrict purestorage.flashblade to < 1.21.0

---

docs/release-managers-mentorship/training.md
docs/release-managers-mentorship/training_resources.md

This adds the definition, expectation  initial plan and steps for  Release Management Mentorship program .  Also shares the resources to be shared during the program. 
This is to be treated like a live document, which evolves as the program continues.

Adds documentation about Release Management Mentorship program 

---

11/ansible-11.build
11/ansible.in
11/collection-meta.yaml
12/ansible-12.build
12/ansible.in
12/collection-meta.yaml
13/ansible-13.build
13/ansible.in
13/collection-meta.yaml

Ref: https://forum.ansible.com/t/44544
Ref: ansible-collections/ansible-inclusion#82

Add hitachivantara.vspone_object
