2.10/acd.in
These collections has been removed from community general into their own
collection under the ngine_io namespace:
- https://github.com/ansible-collections/community.general/pull/173
- https://github.com/ansible-collections/community.general/pull/172
- https://github.com/ansible/ansible/pull/68916
- https://github.com/ansible/ansible/pull/68917
=> add vultr and cloudstack collections

2.10/acd.in
A vendor supported dedicated collections [cloudscale_ch.cloud](https://galaxy.ansible.com/cloudscale_ch/cloud) based on the community.general modules (I and vendor were the only community).
=> dedicated collection for cloudscale.ch related plugins

2.10/acd.in
hetzner.hcloud have done their first release, so we can include that in the next build of `ansible`
https://galaxy.ansible.com/hetzner/hcloud
FYI @LKaemmerling
=> hetzner.hcloud has reached 0.1.0

2.10/acd.in
Just found that NIOS has been split into its own Collection.
Though they've got a fair bit of work to do https://github.com/infobloxopen/infoblox-ansible/issues/7
=> infobox.nios_modules (not available yet)

2.10/acd.in
community.proxysql should be live within the next ~5 days.
Once this is has been published to Galaxy (which I'll do) we can uncomment this line so it's included in the next build of the `ansible` package.
This is been driven by `persysted` (Freenode) (@bmildren)
=> community.proxysql

2.10/CHANGELOG-v2.10.rst
Adds generated changelog to the build data. This allows us to link to the changelog in a common place, similar to the ansible-base changelog for 2.xx being in ansible/ansible#stable-2.xx.
=> Add changelog

2.10/CHANGELOG-v2.10.rst, 2.10/changelog.yaml
This contains among others all the non-base porting guide entries; see ansible/ansible#70891.
=> Extend changelog (and later porting guide) with manual per-release data

2.10/changelog.yaml
This essentially says that the changelog describes changes that happened since Ansible 2.9.0.
=> Add ancestor to changelog.yaml

2.10/changelog.yaml
Will clean up entries when the following PRs are merged:
=> Remove global changelog entries moved to collection changelogs

2.10/ansible.in
1.0.0 has been [released](https://galaxy.ansible.com/community/hrobot), and I'm pretty sure it follows as rules from the checklist.
=> Add community.hrobot

2.10/ansible-2.10.build, 2.10/ansible.in
These are the changes needed to add a new collection to a stable release.  In this PR we add community.okd which was spun out of community.general and thus is allowed into 2.10.x according to the policies approved at the community irc meeting.
I had to do this manually (add the collection name to ansible.in and look on galaxy.ansible.com for the current version and add the collection with the appropriate version range to the ansible-2.10.build file.)  I've opened a ticket on the antsibull repo to add code to do that at some point in the future.
=> Add community.okd, a collection which was broken out of the community.general collection, for 2.10.4

2.10/ansible-2.10.build, 2.10/ansible.in
Including cisco.nso in ansible.in per PR https://github.com/ansible-collections/community.network/pull/142 and 
https://github.com/CiscoDevNet/ansible-nso/issues/4
=> Migrate Cisco NSO modules from community.network to cisco.nso

2.10/ansible-2.10.build, 2.10/ansible.in, 3/ansible.in
[community.hashi_vault 1.0.0](https://galaxy.ansible.com/community/hashi_vault) has been released. It contains the hashi_vault lookup plugin that's migrated from community.general.
Also, since 3/ansible.in is already there, new collections should be added there as well. Since community.google wasn't added there in #45, I'm adding it in this PR as well.
CC @briantist
=> Add community.hashi_vault to 2.10 and 3; add community.google to 3

2.10/ansible-2.10.build, 2.10/ansible.in, 3/ansible.in
1.0 was released and it's contents were migrated from community.general.
=> Add community.kubevirt to 2.10 and 3

3/ansible.in
This collection was reviewed and meets the criteria agreed upon by the
Ansible community and its inclusion to Ansible 3.0 has been approved.
The history of the application as well as the review is available at:
https://github.com/ansible-collections/ansible-inclusion/discussions/5
=> Include t_systems_mms.icinga_director for Ansible 3.0

3/collection-meta.yaml
Since they do not have `changelogs/changelog.yaml`.
=> Add t_systems_mms.icinga_director changelog URL

3/ansible.in, 3/collection-meta.yaml
The community.kubernetes will be renamed to kubernetes.core with its future 2.0 release.
The contents of the community.kubernetes repo are being published to both collection
names on Galaxy today (1.x.x series).
community.okd versions >= 1.0.1 depend on the name kubernetes.core.
https://github.com/ansible-collections/community.kubernetes/issues/221
=> Include kubernetes.core in ansible-3

3/ansible.in, 3/collection-meta.yaml
The history of the application as well as the review is available at:
https://github.com/ansible-collections/ansible-inclusion/discussions/3
=> Include dellemc.openmanage collection for Ansible 3.0

2.10/ansible-2.10.build, 2.10/changelog.yaml
I've added a changelog entry for this change explaining it. 
Before this is done, I have to test how antsibull-build reacts on an existing changelog for a new version. This might either require a fix to antsibull, or some more manual work during release. (Since this should be easier in the future, I prefer a fix to antsibull). Or maybe it already works as expected, I haven't tried this for a long time :)
=> [WIP] Restrict community.okd to 1.0.0 for Ansible 2.10

2.10/porting_guide_2.10.rst
This will help users find out where modules and plugins might have been moved.
=> Update 2.10 porting guide to include module index

4/changelog.yaml
CC @jillr @gravesm can you please take a look at the wording? Thanks :)
=> Add 4.2.0 changelog fragment for community.kubernetes deprecation

5/ansible.in, 5/collection-meta.yaml
This commit adds three collections to the Ansible 5 build data:
* cloud.common,
* infoblox.nios_modules, and
* netapp.storagegrid.
Link to the meeting minutes with votes:
https://meetbot.fedoraproject.org/ansible-community/2021-10-20/ansible_community_meeting.2021-10-20-18.00.html
=> Add accepted candidates to the Ansible 5 build data

5/ansible.in
This is what caused the docs builds to fail...
`   retval = await self._get_galaxy_versions(galaxy_url)
File "/home/samccann/new-ansible/lib64/python3.9/site-packages/antsibull/galaxy.py", line 80, in _get_galaxy_versions
raise NoSuchCollection(f'No collection found at: {versions_url}')
antsibull.galaxy.NoSuchCollection: No collection found at: https://galaxy.ansible.com/api/v2/collections/infobox/nios_modules/versions/
`
=> Fix spelling error in infoblox namespace

5/CHANGELOG-v5.rst, 5/porting_guide_5.rst
#96 accidentally removed the new section 'Added Collections' in porting guide and changelog that was added in #95.
=> Re-add accidentally removed 'Added Collections' sections.

5/porting_guide_5.rst
Output of https://github.com/ansible-community/antsibull/pull/397.
=> Insert ansible-core version in the porting guide.

.github/workflows/antsibull-build-default.yml
The purpose of the job is to build what would be the next version of
ansible, including the changes of the PR, to see if it works.
We were trying to build ansible 5.0.0 in the job because that's what the
role defaults to.
Specify a future (unreleased) version so we can test the build properly.
=> CI: Use version 5.10.0 to test builds in CI

6/ansible-6.build, 6/ansible.in, 6/changelog.yaml
Removal of broken collection community.kubevirt from Ansible 6 (ansible-community/community-topics#92).
cc @felixfontein
=> Remove community.kubevirt from Ansible 6

5/ansible-5.build, 5/ansible.in, 5/collection-meta.yaml, 6/ansible-6.build, 6/ansible.in, 6/collection-meta.yaml
Implements ansible-community/community-topics#99
=> Add vmware.vmware_rest to Ansible 6

5/CHANGELOG-v5.rst, 5/porting_guide_5.rst, 6/CHANGELOG-v6.rst, 6/porting_guide_6.rst
For example, when cisco.dnac is added to Ansible, in the changelog and porting guide release for the version that adds that collection (6.0.0b1) the full condensed changelog of cisco.dnac is contained. This is not helpful for users since there are quite some entries and they do not cover anything that was included in Ansible before (since the collection is new). It's also not helpful for users who manually installed the collection before since they usually didn't install its initial release, but a later version. So it's better to not include all that information.
Result of https://github.com/ansible-community/antsibull/pull/426
=> Avoid including the complete condensed changelog of collections added to Ansible to that Ansible release's changelog and porting guide entries.

.github/workflows/antsibull-build.yml
As of
https://github.com/ansible-community/antsibull/commit/468273f7a28611062c84205e049211ec55b7bc92,
the antsibull build-release role depends on community.general.
Currently, CI jobs fail due to the missing dependency.
=> CI: Install missing build-release role dependency

6/ansible-6.build, 6/ansible.in, 6/collection-meta.yaml, 7/ansible.in, 7/collection-meta.yaml
Add ibm.spectrum_virtualize to Ansible 6
Relates to https://github.com/ansible-community/community-topics/issues/85
=> Add ibm.spectrum_virtualize to Ansible 6

6/changelog.yaml
Deprecate `google.cloud` as discussed in ansible-community/community-topics#105 and voted on in ansible-community/community-topics#121
=> Deprecate google.cloud

7/changelog.yaml
Follow-up to #150.
CC @mariolenz
=> Also announce google.cloud removal in Ansible 7 changelog

6/changelog.yaml, 7/ansible.in
Since `servicenow.servicenow` has been deprecated by its maintainers (ServiceNowITOM/servicenow-ansible#69), we should remove it from Ansible 7 and not do the complete [Unmaintained collections](https://github.com/ansible-collections/overview/blob/main/removal_from_ansible.rst#unmaintained-collections) process and wait until Ansible 8.
Fixes #144
=> Announce removal of servicenow.servicenow in Ansible 7

6/changelog.yaml, 7/changelog.yaml
Deprecate `dellemc.os6` / `9` / `10` as discussed in
- ansible-community/community-topics#132
- ansible-community/community-topics#133
- ansible-community/community-topics#134
and voted on in
- ansible-community/community-topics#139
- ansible-community/community-topics#140
- ansible-community/community-topics#141
=> Deprecate dellemc.os6 / 9 / 10

6/changelog.yaml, 7/changelog.yaml
Deprecate mellanox.onyx as discussed in ansible-community/community-topics#136 and voted on in ansible-community/community-topics#144
=> Deprecate mellanox.onyx

6/ansible-6.5.0.deps
This will fail until https://github.com/ansible-community/antsibull/pull/452 has been merged.
=> Add back the Python information

7/collection-meta.yaml, README.md
In https://github.com/ansible-community/community-topics/issues/148, we discussed implementing a check to make sure that collections in the Ansible package actually tag releases. Having a list of the collections' repository URLs is a necessary prerequisite. This will also allow for other possibilities in the future if we decide to implement other checks or build process changes or something else! In addition to the `repository` field, I added a `collection-directory` field so we can account for collections that are located in a subdirectory of their respective repository.
I added documentation for these new changes and reformatted the existing documentation. I chose `collection-directory` and `repository` as the field names, but I'm open to suggestions.
=> Store collections' repository URLs in collection-meta.yaml

7/changelog.yaml, 8/changelog.yaml
Deprecate community.fortios as discussed in ansible-community/community-topics#162 and voted on in ansible-community/community-topics#179
=> Deprecate community.fortios

README.md
Add release blocker WF
Relates to https://github.com/ansible-community/community-topics/issues/178
Note: I intentionally don't use the term `bug` used in [Fedora project FAQ](https://fedoraproject.org/wiki/Blocker_Bug_FAQ) not to narrow the definition as it can be a core feature missed somehow or whatever.
=> Add release blocker WF

7/changelog.yaml, 8/changelog.yaml
Deprecate
1. community.google as discussed in ansible-community/community-topics#160 and voted on in ansible-community/community-topics#181
2. community.skydive as discussed in ansible-community/community-topics#171 and voted on in ansible-community/community-topics#182
=> Deprecate community.google + community.skydive

7/changelog.yaml, 8/ansible.in, 8/changelog.yaml, 8/collection-meta.yaml
Keep `google.cloud` in Ansible 8 as discussed in ansible-community/community-topics#105 and voted on in ansible-community/community-topics#195.
=> Re-add google.cloud to Ansible 8

.github/workflows/antsibull-build.yml
antsibull is moving away from poetry, so we instead use pip to install antsibull and friends.
=> CI: use `pip` instead of `poetry install`

.github/workflows/antsibull-build.yml
antsibull-core needs to be installed from the local checkout, and
antsibull-docs is no longer a dependency of antsibull.
Fixes: 303c42f966fc0ae805f2421a04a831c42a1a6462
=> CI: use `pip` instead of `poetry install` (take 2)

7/validate-tags-ignores, 8/validate-tags-ignores
These are ignores files for the new collection tag policy enforcement proposal. These files silence release tag validation errors for the listed collection. Currently, those validation errors are treated as warnings.
I will also add docs for this.
Depends-on: https://github.com/ansible-community/antsibull/pull/518
=> add validate-tags-ignores files

8/ansible-8.build
dellemc.enterprise_sonic has depclosure errors. This pins it to the last
working version. Normally, we wouldn't use ==, but since 2.0.0 is the
only release in the range.
```
ERROR: found collection dependency
ERROR: dellemc.enterprise_sonic version_conflict: ansible.netcommon-5.1.1 but needs >=2.0.0,<5.0.0
```
Relates: https://github.com/ansible-community/ansible-build-data/issues/233
Relates: https://github.com/ansible-collections/dellemc.enterprise_sonic/issues/267
=> 8: pin dellemc.enterprise_sonic to 2.0.0

7/ansible-7.build, 8/ansible-8.build
I know we decided not to make this a release blocker until 9.0.0a1, but I'd still like to avoid shipping more untagged collections in releases. Tuesday's releases would happen whether or not this is merged.
Relates: https://github.com/cyberark/ansible-security-automation-collection/issues/58
=> Pin cyberark.pas due to taging policy violations

7/ansible-7.build, 8/ansible-8.build
This reverts commit 0592a32a90d803297748b9f323b9f487d5e007a9.
Closes: https://github.com/cyberark/ansible-security-automation-collection/issues/58
=> Revert "Pin cyberark.pas due to tagging policy violations"

8/changelog.yaml
Deprecate netapp.aws as discussed in ansible-community/community-topics#223 and voted on in ansible-community/community-topics#229
=> Deprecate netapp.aws

8/ansible-8.build, 8/changelog.yaml
The breaking change in dellemc.enterprise_sonic has been reverted (see https://github.com/ansible-collections/dellemc.enterprise_sonic/issues/268), and the restriction to ansible.netcommon < 5.0.0 has been lifted (see https://github.com/ansible-community/ansible-build-data/issues/233). Therefore we remove the pin to 2.0.0 for Ansible 8.
Resolves https://github.com/ansible-collections/dellemc.enterprise_sonic/issues/267
Resolves https://github.com/ansible-collections/dellemc.enterprise_sonic/issues/268
Resolves https://github.com/ansible-community/ansible-build-data/issues/233
=> Ansible 8: allow dellemc.enterprise_sonic != 2.1.0

7/changelog.yaml
I thought that 7.6.0 would be the last 7.x release, but since it looks like there will be a 7.7.0 we should mention the deprecation of netapp.aws there.
This is kind of a backport of #242
=> Deprecate netapp.aws in 7.7.0

7/ansible-7.build
While Ansible 7 is EOL, it is still used in CI (for antsibull-core and antsibull). Now dellemc.os10 has a new release (it was already tagged in March, but only published on Galaxy yesterday) that restricts its ansible.netcommon dependency to < 4.0.0, which contradicts ansible.netcommon >= 4.0.0 in Ansible 7. This makes CI fail in the antsibull-core and antsibull repositories.
Ref: https://github.com/ansible-community/antsibull-core/actions/runs/5440478551/jobs/9893441001
Ref: https://github.com/ansible-community/antsibull/actions/runs/5440539601/jobs/9893565581
=> Ansible 7: restrict dellemc.os10 to <= 1.1.1

docs/release-process.md
Relates: https://github.com/ansible-community/ansible-build-data/issues/221
=> Add initial release-process.md

9/validate-tags-ignores
Currently CI is broken because t_systems_mms.icinga_director 2.0.0 is not tagged - the repository has been renamed.
=> Ignore missing git tag for t_systems_mms.icinga_director

8/changelog.yaml, 9/changelog.yaml
`community.sap` has been renamed and there should have been deprecated redirects to the new collections. Somehow, this never happened. But now there is finally a new release implementing those redirects, so we should announce this again and remove the collection in Ansible 10.
See ansible-community/community-topics#247 for more information and links to the old discussions.
=> Deprecate community.sap (again)

9/validate-tags-ignores
Since the t_systems_mms.icinga_director 2.0.1 release the ignore is no longer necessary.
Ref: #261
=> 9: remove no longer necessary ignore

8/ansible-8.build, 8/ansible.in, 8/changelog.yaml, 8/collection-meta.yaml, 9/ansible.in, 9/changelog.yaml, 9/collection-meta.yaml
We renamed our company and thus the collection-namespace here: https://github.com/ansible/galaxy/issues/3174
The collection now lives here: https://github.com/telekom-mms/ansible-collection-icinga-director
I released a new major version 2.0.0 in the old namespace (https://galaxy.ansible.com/t_systems_mms/icinga_director) where I added the plugin-routing to the new namespace. I also deprecated the collection in the galaxy.
This way I hope in Ansible 8 the old collection will stay the same while in Ansible 9 the new collection will be used.
=> replace t_systems_mms with telekom_mms

8/changelog.yaml, 9/changelog.yaml
Deprecate netapp.elementsw as discussed in ansible-community/community-topics#235 and voted on in ansible-community/community-topics#250
=> Deprecate netapp.elementsw

8/changelog.yaml, 9/ansible.in, 9/changelog.yaml, 9/collection-meta.yaml
Deprecate ngine_io.vultr and remove it from Ansible 9 as discussed in ansible-community/community-topics#257 and voted on in ansible-community/community-topics#259
=> Remove ngine_io.vultr from Ansible 9

8/changelog.yaml, 9/changelog.yaml
Deprecate netapp.um_info
Deprecate netapp.um_info as discussed in ansible-community/community-topics#244 and voted on in ansible-community/community-topics#261
=> Deprecate netapp.um_info

8/collection-meta.yaml, 9/collection-meta.yaml
Old repository: https://github.com/CiscoDevNet/ansible-meraki
New repository: https://github.com/meraki/dashboard-api-ansible
Ref: https://github.com/ansible-community/ansible-build-data/issues/223#issuecomment-1713141024
=> cisco.merkai is now developed in and released from https://github.com/meraki/dashboard-api-ansible

docs/release-process.md
Using environment variable syntax makes values easier to copy and paste.
=> docs/release-process.md: change placeholder value syntax

8/ansible-8.build, 8/ansible.in, 8/changelog.yaml, 8/collection-meta.yaml, 9/ansible-9.build, 9/ansible.in, 9/changelog.yaml, 9/collection-meta.yaml
~~Unfortunately step 4 from the checklist (#306) cannot be implemented since the original repository has been archived already.~~
~~Because of that I marked this PR as a draft, since the changelog entries now don't really make sense.~~
Closes #306.
=> Add ibm.storage_virtualize, which ibm.spectrum_virtualize was renamed to

8/ansible-8.constraints, 9/ansible-9.constraints
Add constraints for Ansible 8 and 9 builds to stick to the last tagged version.
Ref: https://github.com/fortinet-ansible-dev/ansible-galaxy-fortios-collection/issues/277
=> fortinet.fortios 2.3.4 has not been tagged

docs/policies.md
=> Update version tagging enforcement documentation

docs/policies.md
- docs/policies.md: unwrap tagging violation issue template
- docs/policies.md: fix extra word in issue template
=> docs/polices.md: refine tagging violation issue template

docs/release-process.md
There was one placeholder value missed in f9a48c3a160c2464df059cbb9c01658108f115c7.
Relates: f9a48c3a160c2464df059cbb9c01658108f115c7
=> docs/release-process.md: use consistent placeholder syntax

8/ansible-8.constraints
This reverts commit 6fd2b9dc86f5b4d2dd6ed4714307ac65f29ef751.
Ref: https://github.com/ansible-community/ansible-build-data/issues/223#issuecomment-1799356142
=> Revert "8: pin purestorage.flasharray to previous release"

README.md
In the forum, it was was remarked that it is not clear what kind of issues can and should be created in this repository's issue tracker. This PR adds a section at the top of the README with some details on what can (and what should not be) handled here.
Ref: https://forum.ansible.com/t/trying-to-get-a-message-to-the-right-team-about-a-8-6-release-issue/2274/3
=> README: clarify what the issue tracker covers

docs/new-ansible-and-freezes.md
Fixes: https://github.com/ansible-community/ansible-build-data/issues/324
Relates: https://github.com/ansible-community/ansible-build-data/issues/221
=> docs: add new-ansible-and-freezes documentation

docs/new-ansible-and-freezes.md
There should be a paragraph break between `Release Date:` and the
Porting Guide link.
=> new-ansible-and-freezes: fix changelog block indentation

10/ansible-10.constraints
`vmware.vmware_rest` 3.0.0 has just been released, so I think we can remove the constraint on `cloud.common`.
=> Ansible 10: Remove constraint on cloud.common

10/ansible-10.constraints
```
ERROR: found collection dependency errors!
ERROR: cisco.ise 2.6.2 version_conflict: ansible.utils-3.0.0 but needs >=2.0.0,<3.0
ERROR: cisco.dnac 6.8.1 version_conflict: ansible.utils-3.0.0 but needs >=2.0.0,<3.0
ERROR: cisco.meraki 2.16.16 version_conflict: ansible.utils-3.0.0 but needs >=2.0.0,<3.0
```
=> 10: constrain ansible.utils to <3.0.0

mkdocs.yml
The license is GPLv3 *or later,* and we should link to our own LICENSE
file, not the one in core.
=> mkdocs.yml: fix copyright footer

10/ansible-10.constraints, 8/ansible-8.constraints, 9/ansible-9.constraints
Ref: https://github.com/cisco-en-programmability/dnacenter-ansible/issues/142
Ref: https://github.com/ansible-collections/ibm.storage_virtualize/issues/36
=> Do not use cisco.dnac 6.10.0 and ibm.storage_virtualize 2.2.0

.github/workflows/antsibull-build.yml
Right now it only runs on demand. While there's an antsibull-build regular run in the antsibull repository, it would be nice to also have one here to detect build problems on early.
(I've set the day to run to Thursday, since the weekly CI in antsibull runs on Monday.)
=> Run CI at least once weekly

10/ansible-10.constraints
cisco.ise, the last collection to depend on `ansible.utils<3.0.0`, has
been updated.
Ref: https://github.com/CiscoISE/ansible-ise/issues/112#issuecomment-1865136453
=> 10: remove ansible.utils and ansible.netcommon constraints

10/ansible.in, 10/changelog.yaml, 10/collection-meta.yaml
Fixes #285
Remove hpe.nimble from Ansible 10 as discussed in ansible-community/community-topics#254 and announced in #284
=> Remove hpe.nimble from Ansible 10

10/ansible.in, 10/changelog.yaml, 10/collection-meta.yaml
Fixes #249
Remove gluster.gluster from Ansible 10 as discussed in ansible-community/community-topics#225 and announced in #248
=> Remove gluster.gluster from Ansible 10

10/ansible.in, 10/changelog.yaml, 10/collection-meta.yaml
Fixes #276
Remove netapp.elementsw from Ansible 10 as discussed in ansible-community/community-topics#235 and announced in #275
=> Remove netapp.elementsw from Ansible 10

10/ansible.in, 10/changelog.yaml, 10/collection-meta.yaml
Fixes #243
Remove netapp.elementsw from Ansible 10 as discussed in ansible-community/community-topics#223 and announced in #242
=> Remove netapp.aws from Ansible 10

10/ansible.in, 10/changelog.yaml, 10/collection-meta.yaml
Fixes #272
Remove netapp.azure from Ansible 10 as discussed in ansible-community/community-topics#234 and announced in #271
=> Remove netapp.azure from Ansible 10

10/ansible.in, 10/changelog.yaml, 10/collection-meta.yaml
Fixes #280
Remove netapp.um_info from Ansible 10 as discussed in ansible-community/community-topics#244 and announced in #279
=> Remove netapp.um_info from Ansible 10

10/ansible.in, 10/changelog.yaml, 10/collection-meta.yaml
Fixes #266
Remove community.sap from Ansible 10 as discussed in ansible-community/community-topics#247 and  announced in #262
=> Remove community.sap from Ansible 10

docs/release-process.md
At least on my system, the UNIX username is different than my Github
username. Let's change this var name accordingly so it can be more
easily copy-pasted.
=> docs release-process: use GH_USERNAME as a placeholder

10/changelog.yaml, 9/changelog.yaml
Deprecate netapp.storagegrid as discussed and voted on in [Unmaintained collection: netapp.storagegrid](https://forum.ansible.com/t/2811)
=> Deprecate netapp.storagegrid

10/ansible.in, 10/changelog.yaml, 10/collection-meta.yaml, 9/changelog.yaml
Remove purestorage.fusion from Ansible 10 as discussed and voted on in [Deprecation/Removal of purestorage.fusion from the community Ansible package](https://forum.ansible.com/t/3712)
=> Remove purestorage.fusion from Ansible 10

.github/workflows/ansible-release.yml
This exposes the release artifact download URL in the PR body so we can access it while reviewing the release PR.
=> cd ansible-release: include artifact URL in PR body

10/ansible-10.constraints
Due to:
ERROR: cisco.dnac 6.13.1 version_conflict: ansible.utils-4.0.0 but needs >=2.0.0,<4.0
ERROR: cisco.meraki 2.17.2 version_conflict: ansible.utils-4.0.0 but needs >=2.0.0,<4.0
ERROR: cisco.ise 2.8.0 version_conflict: ansible.utils-4.0.0 but needs >=2.0.0,<4.0
=> Restrict ansible.utils to < 4.0.0 for now

10/ansible-10.constraints
This reverts commit d10d57b25884b79ffb4c0ccdd9c6a0ef71f39f33.
All three collections released new versions.
=> Revert "Restrict ansible.utils to < 4.0.0 for now. (#382)"

.github/workflows/ansible-release.yml
The first commit stores the PR's URL and adds a step before uploading the release to PyPI which checks whether the PR has been merged. If it hasn't been merged, the `publish` stage fails. (This isn't the best solution possible, but will prevent something like the accidental 9.5.0 release from today.)
The second commit adds a Python step that parses the package version to validate it, and to extract the major version. This allows to simplify the workflow's input to a single version field.
=> Improve release workflow

9/ansible-9.constraints
community.ciscosmb 1.0.9 reverts the breaking change from 1.0.8.
Closes https://github.com/ansible-collections/community.ciscosmb/issues/75.
=> Undo Ansible 9 pin for community.ciscosmb < 1.0.8

docs/automated-process.md, docs/release-process.md, mkdocs.yml
Based on comments of @gotmax23 in the #release-management:ansible.com room.
=> Document the automated release process

.github/workflows/ansible-release.yml, docs/automated-process.md
=> Allow to create release from existing branch; allow to preserve existing `.deps` and `.build` files; improve docs

.github/workflows/ansible-release.yml
Without this, tagging everything but the latest commit will fail. This happened today when releasing 10.0.0b1: https://github.com/ansible-community/ansible-build-data/actions/runs/9172023176/job/25220255138
=> Release workflow: ensure that all history is there for tagging

docs/automated-process.md
I've done the 9.6.0 and 10.0.0b1 releases today and had some questions about step 5. I think we could improve the documentation here a little bit.
=> Improve Automated Release Process documentation

11/ansible.in, 11/changelog.yaml, 11/collection-meta.yaml
Fixes #363 
Remove inspur.sm from Ansible 11 as discussed in [Unmaintained collection: inspur.sm](https://forum.ansible.com/t/2854) and announced in #362.
=> Remove inspur.sm from Ansible 11

docs/automated-process.md, docs/new-ansible-and-freezes.md
=> Add reference to preparing next major release doc; reference automated workflow from freeze docs

10/ansible-10.build, 10/ansible.in, 10/collection-meta.yaml, 11/ansible.in, 11/collection-meta.yaml
This reverts commit b60fb7b9005b14941a2578a4e648341e4776c5c2.
Reverts PR #419.
Ref: https://github.com/ansible-community/ansible-build-data/pull/419#issuecomment-2169497635
Ref: https://github.com/kubevirt/kubevirt.core/issues/110
Let's re-add it once the dependency on kubernetes.core is less strict.
=> Revert "Add kubevirt.core to Ansible 10 and 11. (#419)"

11/ansible.in, 11/changelog.yaml, 11/collection-meta.yaml
Fixes #373
Remove netapp.storagegrid from Ansible 11 as discussed in [Unmaintained collection: netapp.storagegrid](https://forum.ansible.com/t/2811) and announced in #372.
=> Remove netapp.storagegrid from Ansible 11

10/changelog.yaml, 11/ansible.in, 11/changelog.yaml, 11/collection-meta.yaml, 9/changelog.yaml
Let's remove `frr.frr` and `openvswitch.openvswitch` from Ansible 11 since they _officially_ will not support ansible-core 2.18 (see see [here](https://github.com/ansible-collections/frr.frr/commit/90fa27060a0195a211911398d9959049985bbbba), [here](https://github.com/ansible-collections/frr.frr/commit/69fd7210ae226f66ad8556b28203a357e759e526), [here](https://github.com/ansible-collections/openvswitch.openvswitch/commit/edf3538ed34198f44ced8b7c3dd4501837a69ea0) and [here](https://github.com/ansible-collections/openvswitch.openvswitch/commit/645088eba8ec2b29b196c25559352f583bda0d6e)).
Ref: [Unmaintained collection: frr.frr](https://forum.ansible.com/t/6243)
Ref: [Unmaintained collection: openvswitch.openvswitch](https://forum.ansible.com/t/6245)
Ref: [Several collections have been deprecated …
=> Remove frr.frr and openvswitch.openvswitch

.github/workflows/antsibull-build.yml, .github/workflows/nox.yml
- Check out antsibull-docutils before running antsibull in antsibull-build workflow.
- Clean up nox workflow. It was using the wrong name for the repository, and specified `OTHER_ANTSIBULL_MODE` which isn't used by this repo.
=> Check out antsiubll-docutils, and clean up nox workflow

docs/automated-process.md, docs/release-process.md
Ref: https://github.com/ansible-community/antsibull/pull/613
(That PR actually removes mailing list sending from antsibull.)
=> Remove mentions of the mailing list; copy announce explanation from manual to automated process docs

10/collection-meta.yaml, 9/collection-meta.yaml
Subset of #450 which doesn't have new metadata, but simply reorders the collections. Will rebase that after this is merged.
=> Order collections lexicographically

10/collection-meta.yaml, 11/collection-meta.yaml, 9/collection-meta.yaml
The wti.remote collection uses the standard flat layout as of v1.0.9.
=> all collection-meta: remove collection-directory for wti.remote

.github/workflows/antsibull-build.yml, 10/collection-meta.yaml, 11/collection-meta.yaml, 9/collection-meta.yaml
This is necessary to implement https://github.com/ansible-community/antsibull-docs/issues/93.
Basically there are four ways in this PR that mark a collection for removal. I've added three further possibilities below:
1. It is considered unmaintained:
```yaml
removal:
version: 11
reason: considered-unmaintained
discussion: https://forum.ansible.com/...
announce_version: 9.3.0
```
2. It has officially been deprecated:
```yaml
removal:
version: 11
reason: deprecated
discussion: https://forum.ansible.com/...
announce_version: 9.3.0
```
3. It has been renamed (new name provided) and the removal version is known:
```yaml
removal:
version: 10
reason: renamed
new_name: namespace.name
announce_version: 9.3.0
```
4. It has been renamed (new name provided) and the removal version is not yet known: …
=> Add metadata to indicate which collections are unmaintained / deprecated / will be removed

10/changelog.yaml, 10/collection-meta.yaml, 11/ansible.in, 11/collection-meta.yaml, 9/collection-meta.yaml
The collection was renamed, and replaced by deprecated redirects in Ansible 9. Fix metadata, remove old collection from Ansible 11.
=> t_systems_mms.icinga_director should have been remove from Ansible 11

10/changelog.yaml, 10/collection-meta.yaml, 11/ansible-11.build, 11/ansible.in, 11/changelog.yaml, 11/collection-meta.yaml, 11/galaxy-requirements.yaml, 9/changelog.yaml, 9/collection-meta.yaml
`ngine_io.exoscale` [has been deprecated](https://github.com/ngine-io/ansible-collection-exoscale/commit/f442921cfc8a514c212ccdda1db20355870ef3c5) and should be removed from the Anisble Community Package.
You can find the discussion on the forum [here](https://forum.ansible.com/t/2572).
=> Remove deprecated collection ngine_io.exoscale

10/CHANGELOG-v10.md, 10/CHANGELOG-v10.rst, 10/changelog.yaml, 10/porting_guide_10.rst, 11/CHANGELOG-v11.md, 11/CHANGELOG-v11.rst, 11/changelog.yaml, 11/porting_guide_11.rst, 9/CHANGELOG-v9.md, 9/CHANGELOG-v9.rst, 9/changelog.yaml, 9/porting_guide_9.rst
Use https://github.com/ansible-community/antsibull/pull/623 to automatically generate collection deprecation changelog entries from metadata.
=> Automatically generate collection deprecation changelog entries from metadata

10/CHANGELOG-v10.md, 10/CHANGELOG-v10.rst, 10/collection-meta.yaml, 10/porting_guide_10.rst, 9/collection-meta.yaml
10.0.0a1 removed two more collections that weren't announced in the changelog; this fixes that.
Noticed that while working on #465. The new system should prevent this from happening...
=> Add missing removals

10/ansible-10.constraints, 9/ansible-9.constraints
1.6.0 has a breaking change: the skippy plugin has been removed. This is a semantic versioning violation.
=> Restrict ansible.posix to < 1.6.0

11/ansible-11.constraints
These were added while versions were unbounded. Now it's about time that they somehow match.
=> Ansible 11: remove constraints

10/ansible-10.constraints, 9/ansible-9.constraints
It looks like [ansible.posix 1.6.1](https://github.com/ansible-collections/ansible.posix/releases/tag/1.6.1) reverted the breaking change that has been introduced in 1.6.0. We should undo / revert #469.
Ref: https://github.com/ansible-collections/ansible.posix/commit/cd43bd10bbf4401582ef2305dfc74286b9da05a2
Ref: ansible-collections/ansible.posix#574
=> ansible.posix reverted the breaking change

11/ansible-11.constraints
When trying to do the 11.0.0a2 release I ran into the following error:
```
ERROR: found collection dependency errors!
ERROR: cisco.dnac 6.20.0 version_conflict: ansible.utils-5.1.2 but needs >=2.0.0,<5.0
ERROR: cisco.meraki 2.18.2 version_conflict: ansible.utils-5.1.2 but needs >=2.0.0,<5.0
ERROR: cisco.ise 2.9.3 version_conflict: ansible.utils-5.1.2 but needs >=2.0.0,<5.0
```
It looks like we have a problem there with the following collections:
* [cisco.dnac](https://github.com/cisco-en-programmability/dnacenter-ansible)
* [cisco.meraki](https://github.com/meraki/dashboard-api-ansible)
* [cisco.ise](https://github.com/CiscoISE/ansible-ise)
see also #430
see also #471
=> Ansible 11: temporarily restrict ansible.utils to <5.0.0

10/collection-meta.yaml, 11/collection-meta.yaml, 9/collection-meta.yaml
Relates: https://forum.ansible.com/t/8609
Relates: https://github.com/ansible-community/ansible-build-data/issues/476
=> Schedule google.cloud for removal from Ansible 12

.github/workflows/antsibull-build.yml
Sometimes it's nice to be able to "just run" the workflow, for example to check whether certain releases from outside the repository broke/fixed a build. Right now this requires to create a PR to trigger CI.
=> Allow to trigger antsibull-build workflow manually

.github/workflows/ansible-release.yml, .github/workflows/antsibull-build.yml, docs/automated-process.md, docs/policies.md, docs/release-process.md
https://github.com/ansible-community/antsibull-build/issues/627
=> antsibull has been renamed to antsibull-build

10/changelog.yaml, 11/CHANGELOG-v11.md, 11/CHANGELOG-v11.rst, 11/changelog.yaml, 11/porting_guide_11.rst, 9/changelog.yaml
This is the output of https://github.com/ansible-community/antsibull-build/pull/639. I used it to remove the ansible.posix changelog entry that announces removal of a plugin (that was reverted).
~~Currently contains #486, will rebase once that's merged.~~
Ref: https://github.com/ansible-community/ansible-build-data/pull/478#issuecomment-2408451508
=> Remove specific entries from Ansible changelog

11/ansible-11.build, 11/ansible.in, 11/collection-meta.yaml
We discussed the vote and [action on it on Monday](https://forum.ansible.com/t/2811/28) at today's community meeting. My interpretation of the process was definitely wrong, in case of missed quorum we should have re-added the collection. (We need to improve the formulation (right now it's quite convoluted) and also to clarify some other aspects.) We decided to do another beta release, 11.0.0b1, today with netapp.storagegrid re-added.
This is a resurrection of #489.
=> Re-add netapp.storagegrid to Ansible 11

10/collection-meta.yaml, 11/CHANGELOG-v11.md, 11/CHANGELOG-v11.rst, 11/ansible-11.build, 11/collection-meta.yaml, 11/porting_guide_11.rst, 9/collection-meta.yaml
Resurrection of #488, continues #495, updates #496. See #495 for why we re-added netapp.storagegrid.
(Like its predecessor, needs https://github.com/ansible-community/antsibull-core/pull/177 and https://github.com/ansible-community/antsibull-build/pull/640.)
=> Properly cancel deprecation of netapp.storagegrid

10/collection-meta.yaml, 11/collection-meta.yaml, 12/ansible.in, 12/collection-meta.yaml, 9/CHANGELOG-v9.md, 9/CHANGELOG-v9.rst, 9/collection-meta.yaml, 9/porting_guide_9.rst
The collection hasn't been replaced by redirects *again*, so let's just remove it.
Closes #306.
See also https://forum.ansible.com/t/8119
=> Remove ibm.spectrum_virtualize from Ansible 12

11/collection-meta.yaml, 12/ansible.in, 12/collection-meta.yaml
Fixes #508
The collection has been deprecated.
See also https://forum.ansible.com/t/38960
=> Remove cisco.asa from Ansible 12

.github/workflows/antsibull-build.yml
CI currently fails due to https://github.com/meraki/dashboard-api-ansible/issues/76. Will create another PR which pins cisco.meraki to 2.18.3 for the remaining active versions.
=> Remove EOL'ed Ansible versions from CI matrix

11/ansible-11.constraints, 12/ansible-12.constraints, 8/ansible-8.constraints
Ref: https://github.com/ansible-collections/vmware.vmware/issues/124
Ref: https://github.com/ansible-community/ansible-build-data/issues/223#issuecomment-2679143897
=> Restrict vmware.vmware to < 1.10.1 because 1.10.1 is not tagged

11/ansible-11.constraints, 12/ansible-12.constraints, 8/ansible-8.constraints
It looks like the collection is correctly tagged now, so lets' undo #519.
=> Un-restrict vmware.vmware

11/ansible-11.constraints, 12/ansible-12.constraints
Closes https://github.com/ansible-collections/ibm.storage_virtualize/issues/57.
Ref: #223
=> Remove restriction of ibm.storage_virtualize to <2.7.2

12/ansible-12.constraints
See the comments in the constraints file. This is needed until all collections update their version pins.
=> Temporarily pin ansible.utils to <6.0.0

11/ansible-11.constraints, 12/ansible-12.constraints, 8/ansible-8.constraints
For Ansible 12 this is temporary, since there we'll have ansible.utils 6.x.y, but for Ansible 11 and 8 (needed for ansible-core CI) it's permanent.
Ref: https://github.com/cisco-en-programmability/dnacenter-ansible/issues/254#issuecomment-2853273743
=> Restrict cisco.dnac to <6.32.0 since it needs ansible.utils>=6

.github/workflows/antsibull-build.yml, .github/workflows/nox.yml
Right now they run once per week (on Thursday), which can be problematic if a bad release happens afterwards and before the next release (which is usually on Tuesday). I think it would be better to run the test builds daily so we find out early about problems.
=> Run Ansible test builds daily

11/collection-meta.yaml, 12/collection-meta.yaml
Ref: https://github.com/ansible-community/ansible-build-data/pull/559#pullrequestreview-2948183511
To be merged when Ansible 11.8.0 comes up and cisco.ise still has no updates/progress.
=> Announce removal of cisco.ise from Ansible 12 in Ansible 11

11/collection-meta.yaml, 12/ansible-12.build, 12/ansible.in, 12/collection-meta.yaml
Cancel the removal of google.cloud.
Depends on https://forum.ansible.com/t//8609/18
=> Ansible 12: Cancel google.cloud removal

13/ansible-13.constraints
Ref: https://github.com/ansible-collections/ibm.storage_virtualize/issues/74
Ref: #223
=> Ansible 13: Restrict ibm.storage_virtualize to < 3.1.0
